spring:
  profiles:
    active: "local, prod"
---
spring:
  config:
    activate:
      on-profile: local
  main:
    allow-bean-definition-overriding: true
  application:
    name: accident
  data:
    mongodb:
      database: accident
      uri: mongodb://host.docker.internal:27018/accident

server:
  port: 8082
---
spring:
  config:
    activate:
      on-profile: prod

server:
  port: 8083



