spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accident

  data:
    mongodb:
      database: accident
      uri: mongodb://mongodb:27017/accident

server:
  port: 8083


