spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: accident
  data:
    mongodb:
      database: accident
      uri: mongodb://mongodb:27017/accident

server:
  port: 8090

logging:
  file:
    name: accident.log
    path: /
  level:
    root: INFO