spring:
  profiles:
    active: local, prod
---
spring:
  profiles: prod
  main:
    allow-bean-definition-overriding: true
  application:
    name: accident
  data:
    mongodb:
      database: accident
      uri: mongodb://host.docker.internal:27018/accident

server:
  port: 8082
---
spring:
  profiles: local
server:
  port: 8083



