management:
  endpoint:
    shutdown:
      enabled: true

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: rent
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          multiplier: 2

        max-concurrency: 5
        concurrency: 5
    username: guest
    password: guest
    host: rabbitmq
    port: 5672

rabbitmq:
  queue: queue
  queue_get: queueGet
  exchange: application
  exchange_get: applicationGet
  routing-key: application
  routing-key_get: applicationGet

security:
  jwt: javaintensive

logging:
  file:
    name: rent.log
    path: /
  level:
    root: TRACE

