management:
  endpoint:
    shutdown:
      enabled: true

service:
  geolocation:
    url: http://micromongo:8081/location


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: validate
    open-in-view: false
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          multiplier: 2

        max-concurrency: 5
        concurrency: 5
    username: guest
    password: guest
    template:
      exchange: location
      routing-key: location
    host: localhost
    port: 5672



security:
  jwt: javaintensive

api:
  key: 91911d7a0bbe4df9b7491c90511e6e8c

logging:
  file:
    name: internship.log
    path: /
  level:
    root: info

app:
  logging:
    enabled: true
    level: INFO